### ISSUE TITLE
Support for .NETStandard

### ISSUE THREAD

**Issue by cwishva** [autofac/Autofac.Extras.AttributeMetadata#2]
If we can get Support for AttributeMetadata will be great. Not sure this will be under Autofac.Extensions.DependencyInjection or Autofac.Extras.AttributeMetadata is going to support .NetCore

**Comment by tillig** [comment]
We can't add support for this entire library because it uses MEF, which is full .NET only.

However, there are two logical halves to this package - the half that enables attributes to define metadata and the half that adds parameter filtering by attribute.

The filtering doesn't use MEF.

I'm curious if it might be worth splitting the library... Or moving the filtering to core Autofac... Or something like that to at least get some of the functions compatible with .NET Core.

@alexmg what do you think?

**Comment by alexmg** [comment]
While MEF 1 (`System.ComponentModel.Composition`) has not been ported to .NET Core, it looks like MEF 2 (`System.Composition`) has been ported, so it would be worth looking to see if we can update `Autofac.Integration.Mef` and `Autofac.Extras.AttributeMetadata` to use `System.Composition`.

https://weblogs.asp.net/ricardoperes/using-mef-in-net-core

I have no idea at this point if it will be possible to migrate these packages but will start by having a look at the `Autofac.Integration.Mef` package. My gut feeling is that it won't be straight forward.

**Comment by tillig** [comment]
[I've looked at that in the past.](https://github.com/autofac/Autofac.Mef/issues/7) It's very different - different enough that it might warrant a whole separate package. That's why splitting the filtering from the strong metadata attribute stuff may add some portability.

Technically the filtering could even be part of core Autofac it's so standalone.

**Comment by alexmg** [comment]
It didn't take long to come to the same conclusion. In fact after I started looking at it, I had a strange feeling that you had been down this road before. That would definitely be a new MEF2 integration package and not an upgrade to the existing MEF package. Not something I'm keen to add into the mix unless there really was demand. The first obvious issue was the `Lazy<T, TMetadata>` type only being present in `System.ComponentModel.Composition`.

I think the filtering would be a good candidate to move into core. It's a clever trick and I can see the appeal of having keys defined explicitly on the constructor like that so you don't have to track down the registration to find out which keyed service is being injected. The coupling to the library that such a feature introduces might not sit well with everyone, but if they don't want that they can keep the keyed lookup in the registration instead. The way the metadata filtering is applied is also pretty cool. When not used, both key and metadata filtering wouldn't impose any performance cost at time of registration or runtime, so that wouldn't be an issue if we moved it to core.

There probably isn't much we can do about the attributed metadata extraction as we don't support interface based metadata in core, and having the attribute implement the metadata interface is kind of key to how the feature works.

@chanaka1 Was it the attributed metadata or attributed filtering that you were most interested in using in .NET Core?

**Comment by cwishva** [comment]
I was interested on a attributed filter. 
Example when i have multiple implementation of the same interface if i can say in the constructor [WithKey("Implementation2")] Or [WithName("Implementation1")] that's what i am looking for. 

I know that we can do that with index rite now. The filter would make it cleaner for me.

**Comment by tillig** [comment]
Excellent. That's the part I think we could move into core Autofac.

From a logistics perspective, it's probably like how we moved `InstancePerRequest` in:

- Add the functions to core Autofac with slightly different names to avoid breaking people with the existing library.
- Update this library to require a new minimum version of Autofac with the new functions.
- Pass the existing functions through to the new ones in core and mark the existing ones obsolete.

I don't think that's breaking so probably a 0.1 semver increase.

**Comment by alexmg** [comment]
I have moved the attribute filter feature into core in the `Autofac.Features.AttributeFilters` namespace and bumped the version to 4.2.2.

The names have not yet been changed to prevent clashes and the `Obsolete` attributes still need to be added to the `Autofac.Extras.AttributedMetadata` package along with the version pinning. Hopefully I can get to the second phase in the next day or two.

**Comment by alexmg** [comment]
I have done some renames on the attribute filtering types.

`WithMetadataAttribute` -> `MedataFilterAttribute`
`WithKeyAttribute` -> `KeyFilterAttribute`

```
public SolutionExplorerMixed(
	[WithMetadata("Target", "Solution")] IEnumerable<IAdapter> adapters, 
	[WithKey("Solution")] ILogger logger))

public SolutionExplorerMixed(
	[MetadataFilter("Target", "Solution")] IEnumerable<IAdapter> adapters, 
	[KeyFilter("Solution")] ILogger logger)
```
	
I think I like these attribute names better as they explicitly indicate the attribute value will be used as a filter.

`RegistrationExtensions.WithAttributeFilter` -> `RegistrationExtensions.WithAttibuteFiltering`

```
builder.RegisterType<SolutionExplorerMixed>().WithAttributeFilter(); 

builder.RegisterType<SolutionExplorerMixed>().WithAttributeFiltering(); 
```

I also like this name better as more than one attribute filter can be applied.

In terms of redirection from the existing library:

- `WithAttributeFilter` method can be redirected to `WithAttributeFiltering` in core.
- `WithAttributeFilter` can be marked as obselete with guidance to use `WithAttibuteFiltering` in core.
- `ParameterFilterAttribute` can be deleted and replaced with the one from core.
- `WithKeyAttribute` and `WithMetadataAttribute` can be updated to inherit from `ParameterFilterAttribute` in core.
- `WithKeyAttribute` and `WithMetadataAttribute` can be marked as obselete with guidance to use `KeyFilterAttribute` and `MedataFilterAttribute`.

**Comment by tillig** [comment]
If we remove the `ParameterFilterAttribute` that could break some folks since it's public/abstract. I'm curious if it'd be better to just derive the one here from the one in core and mark the one here as obsolete. That should also allow peoples' custom filters - if they have any - to continue working while being indirectly seen as obsolete.

**Comment by alexmg** [comment]
I ended up just marking the attributes and registration extension as obsolete. The implementation in the core library is in a different namespace and shouldn't clash with any existing code. This is now ready to have the version dependency on Autofac core bumped once that is released.

**Comment by alexmg** [comment]
I think it's time for a 4.2.2 release of Autofac core. What do you think @tillig? Is there anything else you want to see in that point release?

**Comment by tillig** [comment]
If it includes the new filtering features, it's a 0.1 increment, so 4.3.0, not 4.2.2. Other than that, no reason to hold it back. Release early, release often, right?

**Comment by alexmg** [comment]
I have released Autofac 4.3.0 with the attribute filtering capability to NuGet.

**Comment by alexmg** [comment]
I reopened as I haven't yet pushed out a new `Autofac.Extras.AttributedMetadata` package. Given we are now forcing the Autofac dependency up from 3.4.0 to 4.3.0 due to the `Obsolete` attributes I think this should probably be a 4.1.0 release. The changes aren't directly breaking but the Autofac dependency upgrade is a significant jump. It feels like more than a PATCH version (backwards-compatible bug fix). /cc @tillig

**Comment by alexmg** [comment]
I have updated the `Component Metadata / Attribute Metadata` documentation to reflect the changes.

http://docs.autofac.org/en/latest/advanced/metadata.html#use-metadata-filters-on-consumers

I kept the original flow of the document to avoid breaking the sample code but highlighted where the attributes and extension method could be found, and that it was not necessary to have custom metadata attributes to perform attribute based filtering.

**Comment by tillig** [comment]
@alexmg I think a 0.1 release for `Autofac.Extras.AttributeMetadata` is reasonable given the changes in requirements and potential API impact (`Obsolete` seems to come up as an error rather than a warning in some newer projects).

**Comment by alexmg** [comment]
The 4.0.1 package has been released and pushed to NuGet.

https://github.com/autofac/Autofac.Extras.AttributeMetadata/releases/tag/v4.0.1

http://www.nuget.org/packages/Autofac.Extras.AttributeMetadata

I think that is the best we can do for the moment.

**Comment by cwishva** [comment]
Thanks mates..
